#pragma once
#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <RE/Skyrim.h>
#include <REL/Relocation.h>
#include <SKSE/SKSE.h>
#include <spdlog/sinks/basic_file_sink.h>
#include <algorithm>
#include <array>
#include <cmath>
#include <map>
#include <set>
#include <vector>
#include <unordered_map>
#include <atomic>
#include <mutex>
#ifdef AddForm
#undef AddForm
#endif
namespace logger=SKSE::log;
