import type { Dispatch, SetStateAction } from 'react';
import type { PanelState, Settings } from './types';
import type { WorkshopAction } from './bridge';

export function GeneralSettings({ state, draft, setDraft, send }: { state: PanelState; draft: Settings; setDraft: Dispatch<SetStateAction<Settings>>; send: WorkshopAction }) {
  const binding = state.settings.hotkey;
  const parts = [binding.ctrl && 'Ctrl', binding.shift && 'Shift', binding.alt && 'Alt', binding.key].filter(Boolean);
  return <>
    <div className="section-heading settings-heading"><div><p>GENERAL SETTINGS</p><h2>通用设置</h2></div><span className="settings-status">调整即时预览，保存后保留</span></div>
    <div className="settings-common"><div><h3>工坊快捷键</h3><p>{state.capturingHotkey ? '按下新的组合键，Esc 取消。' : '所有工坊栏目共用，录入后自动保存。'}</p></div><div className="hotkey-combo">{parts.map((part, i) => <span key={String(part)}>{i > 0 && <i>+</i>}<kbd>{part}</kbd></span>)}</div><button className="capture-button" onClick={() => send(state.capturingHotkey ? 'cancelHotkeyCapture' : 'beginHotkeyCapture')}>{state.capturingHotkey ? '取消等待' : '修改工坊快捷键'}</button></div>
    <div className="settings-common"><div><h3>SkyUI 回收快捷键</h3><p>{state.capturingRecyclingHotkey ? '按下新按键，Esc 取消。单独使用左右 Alt / Ctrl / Shift 时，松开完成录入。' : '背包回收无需锻造设施。支持单键或搭配一个修饰键；立即保存到工坊配置，跨存档生效。'}</p></div><div className="hotkey-combo"><kbd>{state.settings.recyclingHotkey?.label ?? '回收模块未就绪'}</kbd></div><button className="capture-button" disabled={!state.settings.recyclingHotkey?.available || state.savingRecyclingHotkey} onClick={() => send(state.capturingRecyclingHotkey ? 'cancelHotkeyCapture' : 'beginRecyclingHotkeyCapture')}>{state.savingRecyclingHotkey ? '正在更新…' : state.capturingRecyclingHotkey ? '取消回收键录入' : '录入回收快捷键'}</button></div>
    {state.settings.recyclingHotkey?.legacyDetected && <p className="forge-hint">检测到旧回收插件仍在加载。请停用 SimpleRecycling.esp 后重启游戏，避免重复回收。</p>}
    <div className="settings-common"><div><h3>回收操作</h3><p>轻按回收一件，箭矢以 10 支为一组。启用长按后，按住一秒再松开可回收当前堆叠，每次最多 10,000 件。</p></div><label><input type="checkbox" aria-label="启用背包回收" checked={state.settings.recyclingHotkey?.enabled ?? true} onChange={e => send('setRecyclingEnabled', { enabled: e.target.checked })} /> 启用背包回收</label><label><input type="checkbox" aria-label="长按回收整组" checked={state.settings.recyclingHotkey?.holdToRecycleStack ?? true} onChange={e => send('setRecyclingStackEnabled', { enabled: e.target.checked })} /> 长按回收整组</label></div>
    <section className="settings-card general-settings-card">
      <label className="setting range-setting"><span className="setting-icon">Aa</span><span className="setting-copy"><h3>界面字号</h3><p>默认正文为 16px，统一缩放装备养护、魔法箭和设置页的文字。</p></span><span className="range-control"><output>{draft.uiFontScale ?? 100}<small>%</small></output><input aria-label="界面字号" type="range" min="80" max="130" step="5" value={draft.uiFontScale ?? 100} onChange={e => setDraft({ ...draft, uiFontScale: Number(e.target.value) })} /><span className="range-labels"><span>80%</span><span>16px · 100%</span><span>130%</span></span></span></label>
      <label className="setting range-setting"><span className="setting-icon">◐</span><span className="setting-copy"><h3>界面透明度</h3><p>数值越高，越容易透过背景看到游戏画面。文字和图标保持清晰。</p></span><span className="range-control"><output>{draft.uiTransparency ?? 16}<small>%</small></output><input aria-label="界面透明度" type="range" min="0" max="60" step="1" value={draft.uiTransparency ?? 16} onChange={e => setDraft({ ...draft, uiTransparency: Number(e.target.value) })} /><span className="range-labels"><span>不透明</span><span>背景透明度</span><span>60%</span></span></span></label>
      <label className="setting toggle-setting"><span className="setting-icon">♪</span><span className="setting-copy"><h3>工坊操作音效</h3><p>启用按钮点击、修复、强化和魔法箭制作结果音效。</p></span><span className="toggle-control"><input aria-label="工坊操作音效" type="checkbox" checked={draft.enableWorkshopSounds} onChange={e => setDraft({ ...draft, enableWorkshopSounds: e.target.checked })} /><span className="toggle-track"><i /></span><b>{draft.enableWorkshopSounds ? '已启用' : '已关闭'}</b></span></label>
      <footer className="setting-actions"><button type="button" onClick={() => setDraft({ ...draft, uiFontScale: 100, uiTransparency: 16, enableWorkshopSounds: true })}>恢复默认外观与音效</button><button type="button" onClick={() => setDraft({ ...draft, uiFontScale: state.settings.uiFontScale, uiTransparency: state.settings.uiTransparency, enableWorkshopSounds: state.settings.enableWorkshopSounds })}>还原已保存设置</button><button className="save" type="button" onClick={() => send('saveGeneralSettings', { uiFontScale: draft.uiFontScale ?? 100, uiTransparency: draft.uiTransparency ?? 16, enableWorkshopSounds: draft.enableWorkshopSounds })}>保存通用设置</button></footer>
    </section>
  </>;
}
