import { useState } from 'react';
import type { WorkshopAction } from '../bridge';
import type { ArrowState } from './types';
import { moveQueue } from './rules';
export function ArrowInventory({ state, action }: { state: ArrowState; action: WorkshopAction }) {
  const [search, setSearch] = useState(''), [filter, setFilter] = useState('all'), [selected, select] = useState<number>();
  const [dragged, drag] = useState<number>();
  const q = state.ammoQueue, ids = q?.ids ?? [];
  const items = state.arrows.filter(a => a.name.toLocaleLowerCase().includes(search.toLocaleLowerCase()) && (filter === 'all' || (filter === 'normal' ? a.family === 'normal' : a.family !== 'normal')));
  const item = items.find(a => a.id === selected) ?? items[0];
  const edit = (next: number[], enabled = q?.enabled ?? false) => action('queueEdit', { ids: [...new Set(next)], enabled });
  return <div className="arrow-inventory">
    <section className="arrow-queue"><header><div><small>YOUR FIRING ORDER</small><h2>使用队列 <span>{ids.length} / {q?.limit ?? 64}</span></h2></div><div className="arrow-controls"><label><input type="checkbox" checked={q?.enabled ?? false} disabled={!q?.available} onChange={e => edit(ids, e.target.checked)} />队列优先</label><button disabled={!q?.available || !ids.some(id => state.arrows.some(a => a.id === id && a.count > 0 && a.usable !== false))} onClick={() => action('queueStart')}>从队首开始</button></div></header>
      <div className="arrow-queue-items">{ids.map((id, index) => { const a = state.arrows.find(a => a.id === id) ?? q?.items?.find(a => a.id === id); return <article key={id} draggable onDragStart={() => drag(id)} onDragEnd={() => drag(undefined)} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); if (dragged !== undefined) edit(moveQueue(ids, dragged, id)); drag(undefined); }}><small>{index + 1} · {a?.equipped ? '使用中' : a?.count ? '等待使用' : '缺货 · 跳过'}</small><b>{a?.name ?? '来源缺失的箭矢'}</b><span>×{a?.count ?? 0}</span><div><button aria-label={`前移${a?.name}`} disabled={!index} onClick={() => edit(moveQueue(ids, id, ids[index - 1]))}>←</button><button aria-label={`后移${a?.name}`} disabled={index === ids.length - 1} onClick={() => edit(moveQueue(ids, id, ids[index + 1]))}>→</button><button aria-label={`移除${a?.name}`} onClick={() => edit(ids.filter(x => x !== id))}>×</button></div></article>; })}{!ids.length && <p className="arrow-muted">将常用箭矢加入队列，持弓时优先使用队首，耗尽后自动切换。</p>}</div>
    </section>
    <div className="arrow-toolbar"><div className="workshop-tabs">{[['all', '全部'], ['normal', '普通'], ['magic', '魔法']].map(([id, name]) => <button key={id} className={filter === id ? 'active' : ''} onClick={() => setFilter(id)}>{name}</button>)}</div><input aria-label="搜索箭矢" placeholder="搜索背包中的箭矢…" value={search} onChange={e => setSearch(e.target.value)} /></div>
    <div className="arrow-columns"><section className="arrow-inventory-grid" aria-label="箭矢网格">{items.map(a => <button key={a.id} className={`arrow-grid-card ${a.id === item?.id ? 'selected' : ''}`} aria-pressed={a.id === item?.id} onClick={() => select(a.id)}><span className={`arrow-sigil ${a.family}`}>➶</span><span><b>{a.name}</b><small>{a.bolt ? '弩矢' : a.family === 'normal' ? '普通箭' : '魔法箭'}{a.equipped ? ' · 已装备' : ''}</small></span><strong>×{a.count}</strong></button>)}{!items.length && <p className="arrow-muted">没有符合条件的箭矢。</p>}</section>
      <aside className="arrow-card arrow-inspector">{item ? <><small>ARROW DETAILS</small><div className={`arrow-art ${item.family}`}>➶</div><h2>{item.name}</h2><div className="arrow-stats"><span>库存<b>{item.count}</b></span><span>物理伤害<b>{Math.round(item.damage)}</b></span><span>使用武器<b>{item.bolt ? '弩' : '弓'}</b></span></div><p>{item.usable === false ? '原法术或基材引用不可用，暂时无法装备。' : item.spellBound ? item.adapter?.releaseMode === 'sustained' ? '命中后持续释放封存法术 3 秒。' : '命中后释放封存法术，归属实际射手。' : item.family === 'normal' ? '可作为对应法术的制作基材。' : '仅有外观效果，尚未封存法术。'}</p><button className="arrow-primary" disabled={item.equipped || item.usable === false || !item.count} onClick={() => action('equip', { id: item.id })}>{item.equipped ? '当前已装备' : '装备箭矢'}</button><button disabled={!q?.available || item.bolt || item.usable === false || !item.count || ids.includes(item.id) || ids.length >= (q?.limit ?? 64)} onClick={() => edit([...ids, item.id], ids.length ? q?.enabled : true)}>{ids.includes(item.id) ? '已加入队列' : '＋ 加入使用队列'}</button><small>装备时工坊会关闭，以便角色完成装备动作。</small></> : <p>选择一组箭矢查看详情。</p>}</aside>
    </div>
  </div>;
}
