set_xmakever("2.8.2")
includes("../../../reference/example-skse-plugin/lib/commonlibsse-ng")
set_project("MagicArrows")
set_version("0.9.9")
set_languages("c++23")
set_warnings("allextra")
set_policy("package.requires_lock", true)
add_requires("nlohmann_json")
add_rules("mode.release", "mode.debug")
target("MagicArrows")
    add_deps("commonlibsse-ng")
    add_packages("nlohmann_json")
    add_rules("commonlibsse-ng.plugin", {name="MagicArrows", author="linos", description="Magic arrow inventory and workshop panel"})
    add_files("src/**.cpp")
    add_headerfiles("src/**.h")
    add_includedirs("src")
    set_pcxxheader("src/pch.h")
    add_cxxflags("/utf-8")

target("crafting-plan-test")
    set_kind("binary")
    set_default(false)
    add_files("tests/crafting_plan_test.cpp")
    add_includedirs("src")
    add_cxxflags("/utf-8")

target("normal-plan-test")
    set_kind("binary")
    set_default(false)
    add_files("tests/normal_plan_test.cpp")
    add_includedirs("src")
    add_cxxflags("/utf-8")

target("runtime-rules-test")
    set_kind("binary")
    set_default(false)
    add_files("tests/runtime_rules_test.cpp")
    add_includedirs("src")
    add_cxxflags("/utf-8")

target("sustained-rules-test")
    set_kind("binary")
    set_default(false)
    add_files("tests/sustained_rules_test.cpp")
    add_includedirs("src")
    add_cxxflags("/utf-8")

target("follower-rules-test")
    set_kind("binary")
    set_default(false)
    add_files("tests/follower_rules_test.cpp")
    add_includedirs("src")
    add_cxxflags("/utf-8")

target("projectile-rules-test")
    set_kind("binary")
    set_default(false)
    add_files("tests/projectile_rules_test.cpp")
    add_includedirs("src")
    add_cxxflags("/utf-8")

target("script-compatibility-test")
    set_kind("binary")
    set_default(false)
    add_files("tests/script_compatibility_test.cpp")
    add_includedirs("src")
    add_cxxflags("/utf-8")

target("spell-compatibility-test")
    set_kind("binary")
    set_default(false)
    add_files("tests/spell_compatibility_test.cpp")
    add_includedirs("src")
    add_cxxflags("/utf-8")

target("alchemy-cost-test")
    set_kind("binary")
    set_default(false)
    add_files("tests/alchemy_cost_test.cpp")
    add_includedirs("src")
    add_cxxflags("/utf-8")

target("arrow-identity-test")
    set_kind("binary")
    set_default(false)
    add_files("tests/arrow_identity_test.cpp")
    add_includedirs("src")
    add_cxxflags("/utf-8")

target("ammo-queue-test")
    set_kind("binary")
    set_default(false)
    add_files("tests/ammo_queue_test.cpp")
    add_includedirs("src")
    add_cxxflags("/utf-8")
