set_xmakever("2.8.2")
includes("../../../reference/example-skse-plugin/lib/commonlibsse-ng")
set_project("MainMenuManager")
set_version("0.1.0")
set_languages("c++23")
set_warnings("allextra")
add_rules("mode.release", "mode.debug")
add_requires("nlohmann_json")

target("MainMenuCore")
    set_kind("static")
    add_packages("nlohmann_json", {public = true})
    add_includedirs("src", {public = true})
    add_defines("NOMINMAX", "WIN32_LEAN_AND_MEAN", {public = true})
    add_cxxflags("/utf-8")
    add_syslinks("bcrypt", {public = true})
    add_files("src/library.cpp")

target("MainMenuManager")
    set_kind("shared")
    add_deps("commonlibsse-ng", "MainMenuCore")
    add_cxxflags("/utf-8")
    add_files("src/main.cpp")
    -- Packaging is explicit: building never installs into the live game.

target("MainMenuTests")
    set_kind("binary")
    set_default(false)
    add_deps("MainMenuCore")
    add_cxxflags("/utf-8")
    add_files("tests/library.cpp")

target("MainMenuCatalogCheck")
    set_kind("binary")
    set_default(false)
    add_deps("MainMenuCore")
    add_cxxflags("/utf-8")
    add_files("tests/catalog.cpp")
