set_xmakever("2.8.2")
includes("../../../reference/example-skse-plugin/lib/commonlibsse-ng")
set_project("EquipmentWorkshop")
set_version("1.4.2")
set_languages("c++23")
set_warnings("allextra")
set_policy("package.requires_lock", true)
add_requires("nlohmann_json")
add_rules("mode.release", "mode.debug")
target("EquipmentWorkshop")
    add_deps("commonlibsse-ng")
    add_packages("nlohmann_json")
    add_rules("commonlibsse-ng.plugin", {name="EquipmentWorkshop", author="linos", description="Equipment and magic arrow workshop"})
    add_defines("UNIFIED_WORKSHOP")
    add_files("../../durability-manager/native/src/main.cpp", "../../magic-arrows/native/src/main.cpp")
    add_includedirs("src", "vendor")
    set_pcxxheader("../../durability-manager/native/src/pch.h")
    add_cxxflags("/utf-8")
target("WorkshopMigrationTests")
    set_kind("binary")
    set_default(false)
    add_files("tests/migration.cpp")
    add_includedirs("src")

target("WorkshopUIBackendTests")
    set_kind("binary")
    set_default(false)
    add_files("tests/ui_backend.cpp")
    add_includedirs("src", "vendor")
    add_undefines("NDEBUG")
    add_cxxflags("/utf-8")
