set_xmakever("2.8.2")
includes("../../../reference/example-skse-plugin/lib/commonlibsse-ng")
set_project("MusicManager")
set_version("0.3.0")
set_languages("c++23", "c11")
set_warnings("allextra")
add_requires("nlohmann_json")
add_rules("mode.release", "mode.debug")

target("MusicAudio")
    set_kind("static")
    add_files("src/miniaudio.c")
    add_includedirs("vendor", {public = true})
    set_warnings("none")

target("MusicManager")
    add_deps("commonlibsse-ng", "MusicAudio")
    add_packages("nlohmann_json")
    add_cxxflags("/utf-8")
    add_syslinks("shell32")
    add_rules("commonlibsse-ng.plugin", {
        name = "MusicManager", author = "linos",
        description = "Environment playlists with native MP3 playback and Prisma UI"
    })
    add_files("src/**.cpp")
    add_headerfiles("src/**.h")
    add_includedirs("src")
    set_pcxxheader("src/pch.h")

target("MusicRulesTests")
    set_kind("binary")
    set_default(false)
    add_cxxflags("/utf-8")
    add_includedirs("src")
    add_files("tests/rules.cpp")

target("MusicAudioTests")
    set_kind("binary")
    set_default(false)
    add_deps("MusicAudio")
    add_cxxflags("/utf-8")
    add_files("tests/audio.cpp")

target("MusicServiceTests")
    set_kind("binary")
    set_default(false)
    add_deps("MusicAudio")
    add_packages("nlohmann_json")
    add_cxxflags("/utf-8")
    add_defines("MUSIC_SERVICE_TEST", "NOMINMAX")
    add_includedirs("src")
    add_files("tests/service.cpp", "src/music_service.cpp")

target("MusicSettingsTests")
    set_kind("binary")
    set_default(false)
    add_packages("nlohmann_json")
    add_cxxflags("/utf-8")
    add_includedirs("src")
    add_files("tests/settings.cpp")
