"""Build an independent ESL ESP, compile Papyrus, then package for MO2.

Never writes to game/MO2 files. Optional plugins are resolved at runtime.
Binary layouts follow reference/wbDefinitionsTES5.pas; record utility is
copied from companion-manager so this module can build independently.
"""
from pathlib import Path
import argparse
import json
import re
import struct
import subprocess
import zipfile
from plugin_records import records, subrecords, edid, sub, encode, group

ROOT = Path(__file__).resolve().parents[1]
REPO = ROOT.parents[1]
GAME_ROOT = Path('C:/Users/linos/Desktop/games/+skyrim')
U32 = lambda value: struct.pack('<I', value)
Z = lambda value: value.encode('utf8') + b'\0'
QUEST = 0x01000800
IDS = dict(Markers=0x810, Bandits=0x811, Wolves=0x812, Trolls=0x813,
           Beasts=0x814, Extras=0x815, Menu=0x820, Robbery=0x821,
           Directions=0x822, Warning=0x823, Help=0x824,
           SideA=0x830, SideB=0x831, SettingsPower=0x840)

def ws(value):
    raw = value.encode('utf8')
    return struct.pack('<H', len(raw)) + raw

def script(name, props=None):
    props = props or {}
    return ws(name) + b'\0' + struct.pack('<H', len(props)) + b''.join(
        ws(key) + b'\x01\x01' + struct.pack('<HHI', 0, 0xFFFF, value)
        for key, value in props.items())

def vmad(name, props=None):
    return struct.pack('<HHH', 5, 2, 1) + script(name, props)

def record(sig, local, name, body=b''):
    return dict(sig=sig, form=0x01000000 | local, data=sub(b'EDID', Z(name)) + body)

def formlist(local, name, forms=()):
    return record(b'FLST', local, name, b''.join(sub(b'LNAM', U32(f)) for f in forms))

def validate_config(config):
    groups = config['groups']
    if len(groups) > 128:
        raise ValueError('At most 128 optional groups')
    seen = set()
    seen_ids = set()
    for entry in groups:
        key, plugin = entry['key'], entry['plugin']
        if not re.fullmatch(r'[a-z][a-z0-9_]*', key) or key in seen:
            raise ValueError(f'Invalid or repeated group key: {key}')
        seen.add(key)
        local = int(entry.get('id', hex(0x900 + len(seen) - 1)), 0)
        if not 0x900 <= local < 0x980 or local in seen_ids:
            raise ValueError(f'Invalid or repeated pool ID: {key}')
        seen_ids.add(local)
        minimum = entry.get('min_level', 15)
        if type(minimum) is not int or not 1 <= minimum <= 100:
            raise ValueError(f'Invalid minimum level: {key}')
        if not re.fullmatch(r'[^"\\/\r\n]+\.(?:esp|esm|esl)', plugin, re.I):
            raise ValueError(f'Invalid plugin name: {plugin}')
        values = [int(value, 0) for value in entry['forms']]
        if not values or len(values) != len(set(values)) or any(not 0 < v <= 0xFFFFFF for v in values):
            raise ValueError(f'Invalid local form IDs: {key}')
        if 'editor_ids' in entry and len(entry['editor_ids']) != len(values):
            raise ValueError(f'Editor ID count differs from forms: {key}')
    return groups

def build(game_root):
    master = game_root / 'SkyrimSE/Data/Skyrim.esm'
    rows = list(records(master, {b'CELL', b'WRLD', b'REFR', b'NPC_', b'LVLN'}))
    by_name = {edid(row): row for row in rows if row['sig'] in (b'NPC_', b'LVLN')}
    # Bethesda's dedicated scene/travel marker references. Runtime filters to
    # attached Tamriel exterior cells, distance, facing and settlement keywords.
    markers = []
    for row in rows:
        if row['sig'] == b'REFR' and not row['flags'] & (0x20 | 0x800):
            parts = dict(subrecords(row['data']))
            if parts.get(b'XLRT') in (U32(0x4A5FE), U32(0x4A5F5)):
                markers.append(row['form'])
    if not markers:
        raise ValueError('No wilderness markers in master')
    def forms(*names):
        return [by_name[name]['form'] for name in names]
    lists = [formlist(IDS['Markers'], 'WESpawnMarkers', markers),
             formlist(IDS['Bandits'], 'WEBanditPool', forms('LCharBanditMelee1H', 'LCharBanditMelee2H', 'LCharBanditMissile', 'LCharBanditWizard')),
             formlist(IDS['Wolves'], 'WEWolfPool', forms('EncWolf')),
             formlist(IDS['Trolls'], 'WETrollPool', forms('EncTroll', 'EncTrollFrost')),
             formlist(IDS['Beasts'], 'WEBeastPool', forms('EncSabreCat')),
             formlist(IDS['Extras'], 'WEOptionalPools')]
    config = json.loads((ROOT / 'source/pools.json').read_text(encoding='utf8'))
    groups = validate_config(config)
    generated = ['Scriptname WEPools Hidden', '', '; Generated by build.py from pools.json.',
                 'Function Populate(FormList allPools) Global', '    FormList pool', '    Form candidate', '    ActorBase base',
                 '    ; Rebuild runtime additions on load so upgrades remove stale templates.', '    allPools.Revert()']
    for index, entry in enumerate(groups):
        local = int(entry.get('id', hex(0x900 + index)), 0)
        lists.append(formlist(local, 'WEExtra_' + entry['key']))
        generated += [f'    pool = Game.GetFormFromFile(0x{local:08X}, "WildernessEncounters.esp") as FormList',
                      '    If pool != None', '        pool.Revert()']
        for value in entry['forms']:
            generated += [f'        candidate = Game.GetFormFromFile({value}, "{entry["plugin"]}")',
                          '        base = candidate as ActorBase',
                          '        If base != None && !base.IsEssential() && !base.IsProtected() && !base.IsUnique() && !pool.HasForm(candidate)',
                          '            pool.AddForm(candidate)', '        EndIf']
        generated += ['        If pool.GetSize() > 0 && !allPools.HasForm(pool)',
                      '            allPools.AddForm(pool)', '        EndIf', '    EndIf']
    generated += ['EndFunction', '',
                  'Int Function MinimumLevel(FormList pool) Global',
                  '    ; ESL runtime IDs retain the stable local ID in their low 12 bits.',
                  '    Int poolID = Math.LogicalAnd(pool.GetFormID(), 0x00000FFF)']
    for index, entry in enumerate(groups):
        local = int(entry.get('id', hex(0x900 + index)), 0)
        generated += [('    If' if index == 0 else '    ElseIf') + f' poolID == 0x{local:08X}',
                      f'        Return {entry.get("min_level", 15)}']
    generated += ['    EndIf', '    Return 101', 'EndFunction', '',
                  'FormList Function Choose(FormList allPools, Int playerLevel) Global',
                  '    Int size = allPools.GetSize()', '    If size <= 0', '        Return None', '    EndIf',
                  '    Int eligible = 0', '    FormList selected = None', '    Int i = 0',
                  '    While i < size',
                  '        FormList candidate = allPools.GetAt(i) as FormList',
                  '        If candidate != None && candidate.GetSize() > 0 && playerLevel >= MinimumLevel(candidate)',
                  '            eligible += 1', '            If Utility.RandomInt(1, eligible) == 1',
                  '                selected = candidate', '            EndIf',
                  '        EndIf', '        i += 1', '    EndWhile',
                  '    Return selected', 'EndFunction', '']
    (ROOT / 'source/papyrus/WEPools.psc').write_text('\n'.join(generated), encoding='utf-8-sig')

    # Quest VMAD: main script, no fragments, one script bound to player alias 0.
    vm = vmad('WEController', {key: 0x01000000 | value for key, value in IDS.items()})
    vm += struct.pack('<BH', 2, 0) + ws('') + struct.pack('<H', 1)
    vm += struct.pack('<HHIHHH', 0, 0, QUEST, 5, 2, 1) + script('WELoadAlias')
    body = sub(b'VMAD', vm) + sub(b'FULL', Z('野外遭遇'))
    body += sub(b'DNAM', struct.pack('<HBBII', 0x11, 40, 0, 0, 0))
    body += sub(b'NEXT', b'') + sub(b'ANAM', U32(1))
    body += sub(b'ALST', U32(0)) + sub(b'ALID', Z('Player')) + sub(b'FNAM', U32(0))
    body += sub(b'ALFR', U32(0x14)) + sub(b'VTCK', U32(0)) + sub(b'ALED', b'')
    quest = record(b'QUST', 0x800, 'WEControllerQuest', body)

    def message(local, name, text, buttons):
        body = sub(b'DESC', Z(text)) + sub(b'FULL', Z('野外遭遇'))
        body += sub(b'INAM', U32(0)) + sub(b'QNAM', U32(QUEST)) + sub(b'DNAM', U32(1))
        body += b''.join(sub(b'ITXT', Z(button)) for button in buttons)
        return record(b'MESG', local, name, body)
    messages = [
        message(0x820, 'WESettingsMenu', f'野外遭遇 {config["version"]}\n扩展群落：{len(groups)} 组，按等级开放。\n每场3～20名成员，同时最多一场。\n默认频繁：冷却1.5～3.5分钟，需继续行走才会触发。\n剧情文本等待你确认，不会自动消失。\n频率调整会应用于下一场冷却。',
                ['开启 / 暂停新事件', '频繁（冷却减半）', '标准频率', '稀疏（冷却加倍）', '测试随机事件', '关闭']),
        message(0x821, 'WERobbery', '强盗头目：这条路归我们管。交出 %.0f 枚金币，我们就让你过去。\n\n你可以尝试威吓；口才越高，成功机会越大。', ['交钱', '威吓他们', '拒绝，准备战斗']),
        message(0x822, 'WEDirections', '旅人：我们绕了好几圈。前面的路能通到最近的聚落吗？能指个方向吗？\n\n这群人似乎在打量你的装备。', ['停下来指路', '让他们沿大路走，继续赶路']),
        message(0x823, 'WEWarning', '赶路人：小心！前面有怪物出没，我们正准备绕路。你最好也留意身后。', ['听从提醒，放慢脚步', '道谢，继续赶路']),
        message(0x824, 'WEHelp', '赶路人：朋友，有人追了我们一路！我们想在这里守住，能帮忙吗？\n\n周围还有一些来路不明的人，你可以加入战斗，也可以离开。', ['答应帮忙', '拒绝，继续赶路'])]
    factions = [record(b'FACT', 0x830 + i, 'WEEncounterSide' + str(i), sub(b'DATA', U32(0)) +
                       sub(b'XNAM', struct.pack('<IiI', 0x01000830 + (1-i), -100, 1))) for i in range(2)]
    effect = bytearray(152)
    struct.pack_into('<I', effect, 0, 0x0C008E10)
    for offset in (12, 16, 68, 88):
        struct.pack_into('<i', effect, offset, -1)
    struct.pack_into('<I', effect, 64, 1)
    struct.pack_into('<I', effect, 80, 1)
    struct.pack_into('<I', effect, 140, 2)
    mgef = record(b'MGEF', 0x841, 'WESettingsMagicEffect', sub(b'VMAD', vmad('WESettingsEffect')) +
                  sub(b'FULL', Z('野外遭遇设置')) + sub(b'DATA', effect))
    spell = record(b'SPEL', 0x840, 'WESettingsPower', sub(b'OBND', bytes(12)) + sub(b'FULL', Z('野外遭遇设置')) +
                   sub(b'ETYP', U32(0x25BEE)) + sub(b'DESC', Z('调整遭遇频率，暂停新事件，或测试随机遭遇。')) +
                   sub(b'SPIT', struct.pack('<IIIfIIffI', 0, 0xB00001, 3, 0, 1, 0, 0, 0, 0)) +
                   sub(b'EFID', U32(0x01000841)) + sub(b'EFIT', struct.pack('<fII', 0, 0, 0)))
    batches = [(b'FLST', lists), (b'FACT', factions), (b'MGEF', [mgef]), (b'SPEL', [spell]),
               (b'QUST', [quest]), (b'MESG', messages)]
    count = sum(len(items) for _, items in batches)
    header = dict(sig=b'TES4', form=0, flags=0x200, data=sub(b'HEDR', struct.pack('<fII', 1.7, count, 0xA00)) +
                  sub(b'CNAM', Z('linos')) + sub(b'SNAM', Z('Wilderness Encounters ' + config['version'])) +
                  sub(b'MAST', Z('Skyrim.esm')) + sub(b'DATA', bytes(8)))
    data = ROOT / 'data'
    data.mkdir(parents=True, exist_ok=True)
    (data / 'WildernessEncounters.esp').write_bytes(encode(header) + b''.join(group(sig, items) for sig, items in batches))
    (data / 'SEQ').mkdir(exist_ok=True)
    (data / 'SEQ/WildernessEncounters.seq').write_bytes(U32(QUEST))
    print(f'ESP: {count} records, {len(markers)} vanilla spawn markers, {len(groups)} optional groups')
    return config['version']

def compile_scripts(game_root):
    ck = game_root / 'TOOLS/+creation kit'
    source, out = ROOT / 'source/papyrus', ROOT / 'data/Scripts'
    out.mkdir(parents=True, exist_ok=True)
    includes = ';'.join(str(p) for p in (source, game_root / 'SkyrimSE/Data/Scripts/Source', ck / 'Data/Source/Scripts'))
    for name in ('WEPools', 'WEController', 'WELoadAlias', 'WESettingsEffect'):
        result = subprocess.run([str(ck / 'Papyrus Compiler/PapyrusCompiler.exe'), name,
                                 '-i=' + includes, '-o=' + str(out), '-f=' + str(ck / 'Data/Source/Scripts/TESV_Papyrus_Flags.flg')],
                                capture_output=True)
        print((result.stdout + result.stderr).decode('utf8', errors='replace'))
        result.check_returncode()
        if (out / (name + '.pex')).read_bytes()[:4] != bytes.fromhex('fa57c0de'):
            raise ValueError('Invalid compiled script: ' + name)

def package(version):
    target = ROOT / f'packaging/WildernessEncounters-{version}.zip'
    target.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(target, 'w', zipfile.ZIP_DEFLATED) as archive:
        for file in sorted((ROOT / 'data').rglob('*')):
            if file.is_file():
                archive.write(file, file.relative_to(ROOT / 'data').as_posix())
        archive.write(ROOT / 'README.md', 'README.md')
        archive.write(ROOT / 'source/pools.json', 'configuration/pools.json')
        archive.write(ROOT / 'docs/creature-pools.md', 'docs/creature-pools.md')
    print(target)
    return target

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--game-root', type=Path, default=GAME_ROOT)
    parser.add_argument('--records-only', action='store_true')
    args = parser.parse_args()
    version = build(args.game_root)
    if not args.records_only:
        compile_scripts(args.game_root)
        subprocess.run(['python', str(ROOT / 'source/test_plugin.py')], check=True)
        package(version)
