set_xmakever("2.8.2")
includes("../../../reference/example-skse-plugin/lib/commonlibsse-ng")
set_project("ArcaneStaves")
set_version("0.49.1")
set_languages("c++23")
add_rules("mode.release", "mode.debug")
target("ArcaneStaves")
    add_deps("commonlibsse-ng")
    add_rules("commonlibsse-ng.plugin", {name="ArcaneStaves", author="linos", description="Geometric staff spell prototypes for Skyrim SE 1.5.97"})
    add_files("src/main.cpp")
    add_includedirs("src")
    set_pcxxheader("src/pch.h")
    add_cxxflags("/utf-8")
target("staff-rules-test")
    set_kind("binary")
    set_default(false)
    add_files("tests/rules.cpp")
    add_includedirs("src")
    add_cxxflags("/utf-8")
